portal_trabajo/config/routes.rb
Rails.application.routes.draw do
  root "employees#index"
  resources :employees do
      member do
        post "add_employer"
      end
    end

  resources :employers do
    member do
      post "add_employee"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

portal_trabajo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

portal_trabajo/app/models/employee.rb
class Employee < ApplicationRecord
  has_many :offers
  has_many :employers, through: :offers
end

portal_trabajo/app/models/employer.rb
class Employer < ApplicationRecord
  has_many :offers
  has_many :employees, through: :offers
end

portal_trabajo/app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :employer
  belongs_to :employee
end

portal_trabajo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

portal_trabajo/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  def add_employer
    @employee = Employee.find(params[:id])
    @employer = params[:name]
    @employee.employers << Employer.new(name: @employer)
    redirect_to root_path
  end



  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :email, :phone, :cv)
    end
end

portal_trabajo/app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all
  end

  def add_employee
    @employer = Employer.find(params[:id])
    @employee = params[:name]
    @employer.employees << Employee.new(name: @employee)
    redirect_to root_path
  end
  # GET /employers/1
  # GET /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Employer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:name, :email, :phone)
    end
end

portal_trabajo/app/helpers/application_helper.rb
module ApplicationHelper
end

portal_trabajo/app/helpers/employees_helper.rb
module EmployeesHelper
end

portal_trabajo/app/helpers/employers_helper.rb
module EmployersHelper
end

portal_trabajo/app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :cv %>
    <%= form.text_field :cv %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

portal_trabajo/app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

portal_trabajo/app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Cv</th>
      <th>Employer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.cv %></td>

        <td><%= employee.employers.pluck(:name) %>
        <%=form_tag(add_employer_employee_path(employee))do%>
        <%=text_field_tag "name"%>
        <%end%>
        </td>


        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

portal_trabajo/app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

portal_trabajo/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Cv:</strong>
  <%= @employee.cv %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

portal_trabajo/app/views/employers/_form.html.erb
<%= form_with(model: employer, local: true) do |form| %>
  <% if employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

portal_trabajo/app/views/employers/edit.html.erb
<h1>Editing Employer</h1>

<%= render 'form', employer: @employer %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

portal_trabajo/app/views/employers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Empleados</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= employer.name %></td>
        <td><%= employer.email %></td>
        <td><%= employer.phone %></td>
        <td><%= employer.employees.pluck(:name) %>

        <%=form_tag(add_employee_employer_path(employer))do%>
        <%=text_field_tag "name"%>
        <%end%>
      </td>

        <td><%= link_to 'Show', employer %></td>
        <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
        <td><%= link_to 'Destroy', employer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employer', new_employer_path %>

portal_trabajo/app/views/employers/new.html.erb
<h1>New Employer</h1>

<%= render 'form', employer: @employer %>

<%= link_to 'Back', employers_path %>

portal_trabajo/app/views/employers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employer.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employer.phone %>
</p>

<%= link_to 'Edit', edit_employer_path(@employer) %> |
<%= link_to 'Back', employers_path %>

portal_trabajo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortalTrabajo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>